//
// Created by kab2 on 11/25/2024.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURE_MAIN_MEMORY_ADRESS_H
#define ALGORITHMS_AND_DATA_STRUCTURE_MAIN_MEMORY_ADRESS_H


class memory_adress {

};


#endif //ALGORITHMS_AND_DATA_STRUCTURE_MAIN_MEMORY_ADRESS_H
