//
// Created by kab2 on 11/25/2024.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURE_MAIN_POINTERS_H
#define ALGORITHMS_AND_DATA_STRUCTURE_MAIN_POINTERS_H


class pointers {

};


#endif //ALGORITHMS_AND_DATA_STRUCTURE_MAIN_POINTERS_H
